"""
Phase 2 – Mechanical Adjudication
===================================
Sends the assembled context to the best available Ollama node (selected by
NodeRouter) for mechanical resolution.  Dice rolls are generated by the
backend (true-RNG) and injected into the resolution payload.
The Ollama model is FORBIDDEN from generating narrative.

If the primary node fails, NodeRouter will automatically select the next
priority node on the next call.  The health-check loop updates node status
every 30 seconds in the background.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from orchestrator.schemas.payloads import ContextAssemblyPayload, OllamaResolutionPayload

if TYPE_CHECKING:
    from orchestrator.services.node_router import NodeRouter

logger = logging.getLogger(__name__)


class AdjudicationPhase:
    def __init__(self, router: "NodeRouter") -> None:
        self._router = router

    async def resolve(self, context: ContextAssemblyPayload) -> OllamaResolutionPayload:
        """
        1. Ask NodeRouter for the best available Ollama client.
        2. Submit context to that node for mechanical resolution.
        3. True-RNG dice roll is injected by the OllamaClient, not the model.
        """
        logger.info(
            "Phase 2: resolving '%s…' for character %s",
            context.raw_input[:60],
            context.character.character_id,
        )

        ollama     = await self._router.get_ollama_client()
        resolution = await ollama.resolve_action(context)

        logger.info(
            "Phase 2 complete: outcome=%s roll=%d/%d vehicles_affected=%d",
            resolution.outcome.value,
            resolution.roll_result,
            resolution.difficulty,
            len(resolution.state_delta.vehicle_deltas),
        )

        return resolution
