"""
Phase 2 – Mechanical Adjudication
===================================
Sends the assembled context to Ollama. Dice rolls are generated by the
backend (true-RNG) and injected into the resolution payload.
The Ollama model is FORBIDDEN from generating narrative.
"""

from __future__ import annotations

import logging

from orchestrator.schemas.payloads import ContextAssemblyPayload, OllamaResolutionPayload
from orchestrator.services.ollama_client import OllamaClient

logger = logging.getLogger(__name__)


class AdjudicationPhase:
    def __init__(self, ollama: OllamaClient) -> None:
        self._ollama = ollama

    async def resolve(self, context: ContextAssemblyPayload) -> OllamaResolutionPayload:
        """
        Submit context to Ollama and receive the mechanical resolution.
        The dice roll is generated by the backend's true-RNG; Ollama never
        controls randomness directly.
        """
        logger.info(
            "Phase 2: resolving action '%s...' for character %s",
            context.raw_input[:60],
            context.character.character_id,
        )

        resolution = await self._ollama.resolve_action(context)

        logger.info(
            "Phase 2 complete: outcome=%s, roll=%d/%d",
            resolution.outcome.value,
            resolution.roll_result,
            resolution.difficulty,
        )

        return resolution
