#!/usr/bin/env bash
# sync-rules.sh — Assemble modular rule files into agent-specific governance targets.
#
# Usage:
#   bash .ai-rules/scripts/sync-rules.sh          # from repo root
#
# What it produces:
#   .github/copilot-instructions.md   — GitHub Copilot + all AI agent rules
#   CLAUDE.md (rules section only)    — appends/replaces the "## Agent Rules" block
#
# Rule source files (`.ai-rules/rules/NN-*.md`) are concatenated in filename order.
# Edit the source files — never edit the targets directly.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RULES_DIR="$REPO_ROOT/.ai-rules/rules"
COPILOT_OUT="$REPO_ROOT/.github/copilot-instructions.md"
CLAUDE_MD="$REPO_ROOT/CLAUDE.md"

# ── Validate environment ──────────────────────────────────────────────────────

if [ ! -d "$RULES_DIR" ]; then
  echo "ERROR: Rules directory not found: $RULES_DIR" >&2
  exit 1
fi

rule_files=("$RULES_DIR"/[0-9][0-9]-*.md)
if [ ${#rule_files[@]} -eq 0 ] || [ ! -f "${rule_files[0]}" ]; then
  echo "ERROR: No rule files found in $RULES_DIR (expected NN-*.md)" >&2
  exit 1
fi

# ── Build .github/copilot-instructions.md ─────────────────────────────────────

echo "Generating $COPILOT_OUT ..."

{
  echo "# Ironclad GM — Agent Instructions"
  echo ""
  echo "Rules for all AI agents working in this repository."
  echo "Generated by \`sync-rules.sh\` from \`.ai-rules/rules/\` — do not edit this file directly."
  echo ""
  echo "---"
  echo ""

  for f in "${rule_files[@]}"; do
    echo "$(cat "$f")"
    echo ""
  done
} > "$COPILOT_OUT"

echo "  Written: $COPILOT_OUT ($(wc -l < "$COPILOT_OUT") lines)"

# ── Update CLAUDE.md — replace ## Agent Rules block ──────────────────────────

if [ -f "$CLAUDE_MD" ]; then
  echo "Updating $CLAUDE_MD ..."

  # Build the replacement block
  agent_rules_block="## Agent Rules

> Generated from \`.ai-rules/rules/\` by \`sync-rules.sh\`. Edit the source files, not this section.

"
  for f in "${rule_files[@]}"; do
    agent_rules_block+="$(cat "$f")"$'\n\n'
  done

  if grep -q "^## Agent Rules" "$CLAUDE_MD"; then
    # Replace existing block: from "## Agent Rules" to the next "## " heading (or EOF)
    python3 - "$CLAUDE_MD" "$agent_rules_block" <<'PYEOF'
import sys, re

path = sys.argv[1]
new_block = sys.argv[2]

with open(path, 'r') as fh:
    content = fh.read()

# Replace from "## Agent Rules" up to (but not including) the next "## " heading or EOF
pattern = r'(## Agent Rules\n).*?(?=\n## |\Z)'
replacement = new_block.rstrip()
updated = re.sub(pattern, replacement, content, flags=re.DOTALL)

with open(path, 'w') as fh:
    fh.write(updated)
PYEOF
    echo "  Updated existing ## Agent Rules block in $CLAUDE_MD"
  else
    # Append the block at the end
    printf '\n\n---\n\n%s' "$agent_rules_block" >> "$CLAUDE_MD"
    echo "  Appended ## Agent Rules block to $CLAUDE_MD"
  fi
else
  echo "  CLAUDE.md not found — skipping CLAUDE.md update."
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "Sync complete. Files updated:"
echo "  .github/copilot-instructions.md"
[ -f "$CLAUDE_MD" ] && echo "  CLAUDE.md"
echo ""
echo "Commit the updated files alongside any rule changes:"
echo "  git add .ai-rules/rules/ .github/copilot-instructions.md CLAUDE.md"
echo "  git commit -m 'rules: <describe change>'"
